CREATE TABLE TAXONOMY.V_PUBLIC_NODE
(
     TAX_ID DECIMAL(8,0),
     PARENT_ID DECIMAL(8,0),
     HIDDEN DECIMAL(1,0),
     INTERNAL VARCHAR(64),
     RANK VARCHAR(64),
     GC_ID VARCHAR(64),
     MGC_ID VARCHAR(64),
     NCBI_SCIENTIFIC VARCHAR(64),
     NCBI_COMMON VARCHAR(64),
     SPTR_SCIENTIFIC VARCHAR(64),
     SPTR_COMMON VARCHAR(64),
     SPTR_SYNONYM VARCHAR(64),
     SPTR_CODE VARCHAR(64),
     TAX_CODE VARCHAR(64),
     SPTR_FF VARCHAR(64),
     SUPERREGNUM VARCHAR(64),
     SPTR_XML VARCHAR(256),
     TREE_LEFT DECIMAL(8,0),
     TREE_RIGHT DECIMAL(8,0)
);

create table taxonomy.V_PUBLIC_STRAIN
(
    TAX_ID     DECIMAL(8,0),
    STRAIN_ID  DECIMAL(8,0),
    NAME       VARCHAR(64),
    NAME_CLASS VARCHAR(64)
);

create table taxonomy.V_PUBLIC_HOST
(
    TAX_ID      DECIMAL(8,0),
    HOST_ID     DECIMAL(8,0)
);

create table TAXONOMY.V_PUBLIC_URI
(
    TAX_ID  DECIMAL(8,0),
    URI     VARCHAR(64)
);

create table TAXONOMY.V_PUBLIC_NAME
(
    TAX_ID     DECIMAL(8,0),
    PRIORITY   DECIMAL(2,0),
    NAME       VARCHAR(64)
);

create table TAXONOMY.V_PUBLIC_MERGED
(
    OLD_TAX_ID    DECIMAL(8,0),
    NEW_TAX_ID    DECIMAL(8,0)
);

create table TAXONOMY.V_PUBLIC_DELETED
(
    TAX_ID      DECIMAL(8,0)
);
