CREATE TABLE TAXONOMY.V_PUBLIC_NODE
(
     TAX_ID DECIMAL(8,0),
     PARENT_ID DECIMAL(8,0),
     HIDDEN DECIMAL(1,0),
     INTERNAL VARCHAR(64),
     RANK VARCHAR(64),
     GC_ID VARCHAR(64),
     MGC_ID VARCHAR(64),
     NCBI_SCIENTIFIC VARCHAR(64),
     NCBI_COMMON VARCHAR(64),
     SPTR_SCIENTIFIC VARCHAR(64),
     SPTR_COMMON VARCHAR(64),
     SPTR_SYNONYM VARCHAR(64),
     SPTR_CODE VARCHAR(64),
     TAX_CODE VARCHAR(64),
     SPTR_FF VARCHAR(64),
     SUPERREGNUM VARCHAR(64),
     SPTR_XML VARCHAR(256),
     TREE_LEFT DECIMAL(8,0),
     TREE_RIGHT DECIMAL(8,0)
);
