INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (1, null, 1, 0, 'no rank', 1, 0, 'root', null, 'root', null, null, '9ZZZZ', '9ZZZZ', null, 'root', '<name type="scientific">root</name>', 1, 4494384);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10066, 337687, 0, 0, 'family', 1, 2, 'Muridae', null, 'Muridae', null, null, null, '9RODE', 'E', 'Muridae', '<name type="scientific">Muridae</name>', 4397416, 4399987);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10114, 39107, 0, 0, 'genus', 1, 2, 'Rattus', null, 'Rattus', null, null, null, '9MURI', 'E', 'Rattus', '<name type="scientific">Rattus</name>', 4397942, 4398223);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10116, 10114, 1, 0, 'species', 1, 2, 'Rattus norvegicus', 'Norway rat', 'Rattus norvegicus', 'Rat', null, 'RAT', 'RAT', 'E', 'Rattus norvegicus (Rat)', '<name type="scientific">Rattus norvegicus</name>
<name type="common">Rat</name>', 4397953, 4397956);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (39107, 10066, 0, 0, 'subfamily', 1, 2, 'Murinae', null, 'Murinae', null, null, '9MURI', '9MURI', 'E', 'Murinae', '<name type="scientific">Murinae</name>', 4397675, 4399712);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (337687, 1, 0, 0, 'no rank', 1, 2, 'Muroidea', null, 'Muroidea', null, null, null, '9RODE', 'E', 'Muroidea', '<name type="scientific">Muroidea</name>', 4397415, 4403090);

