INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (1, null, 1, 0, 'no rank', 1, 0, 'root', null, 'root', null, null, '9ZZZZ', '9ZZZZ', null, 'root', '<name type="scientific">root</name>', 1, 4494384);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10066, 337687, 0, 0, 'family', 1, 2, 'Muridae', null, 'Muridae', null, null, null, '9RODE', 'E', 'Muridae', '<name type="scientific">Muridae</name>', 4397416, 4399987);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10114, 39107, 0, 0, 'genus', 1, 2, 'Rattus', null, 'Rattus', null, null, null, '9MURI', 'E', 'Rattus', '<name type="scientific">Rattus</name>', 4397942, 4398223);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (10116, 10114, 1, 0, 'species', 1, 2, 'Rattus norvegicus', 'Norway rat', 'Rattus norvegicus', 'Rat', null, 'RAT', 'RAT', 'E', 'Rattus norvegicus (Rat)', '<name type="scientific">Rattus norvegicus</name>
<name type="common">Rat</name>', 4397953, 4397956);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
 VALUES (39107, 10066, 0, 0, 'subfamily', 1, 2, 'Murinae', null, 'Murinae', null, null, '9MURI', '9MURI', 'E', 'Murinae', '<name type="scientific">Murinae</name>', 4397675, 4399712);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (337687, 1, 0, 0, 'no rank', 1, 2, 'Muroidea', null, 'Muroidea', null, null, null, '9RODE', 'E', 'Muroidea', '<name type="scientific">Muroidea</name>', 4397415, 4403090);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (11049, 1, 1, 0, 'no rank', 1, 0, 'Lelystad virus', null, 'Porcine reproductive and respiratory syndrome virus', 'PRRSV', null, 'PRRSL', 'PRRSL', 'V', 'Porcine reproductive and respiratory syndrome virus', '<name type="scientific">Porcine reproductive</name>', 308243, 308246);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (60714, 1, 1, 0, 'species', 1, 0, 'Galinsoga mosaic virus', null, 'Galinsoga mosaic virus', 'GaMV', null, 'GAMV', 'GAMV', 'V', 'Galinsoga mosaic virus (GaMV)', '<name type="scientific">Galinsoga mosaic virus</name><name type="common">GaMV</name>', 303757, 303758);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (289376, 1, 1, 0, 'no rank', 11, 0, 'Thermodesulfovibrio yellowstonii DSM 11347', null, 'Thermodesulfovibrio yellowstonii', null, null, 'THEYD', 'THEYD', 'B', 'Thermodesulfovibrio yellowstonii', '<name type="scientific">Thermodesulfovibrio yellowstonii</name>', 910056, 910057);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (1076255, 1, 1, 0, 'species', 1, 0, 'Yokapox virus', null, 'Yokapox virus', null, null, null, '9POXV', 'V', 'Yokapox virus', '<name type="scientific">Yokapox virus</name>', 420577, 420578);
INSERT INTO TAXONOMY.V_PUBLIC_NODE (TAX_ID, PARENT_ID, HIDDEN, INTERNAL, RANK, GC_ID, MGC_ID, NCBI_SCIENTIFIC, NCBI_COMMON, SPTR_SCIENTIFIC, SPTR_COMMON, SPTR_SYNONYM, SPTR_CODE, TAX_CODE, SUPERREGNUM, SPTR_FF, SPTR_XML, TREE_LEFT, TREE_RIGHT)
VALUES (1559365, 1, 1, 1, 'no rank', 1, 0, 'Turnip curly top virus isolate', null, 'Turnip curly top virus isolate', 'TCTV', null, 'TCTVB', 'TCTVB', 'V', 'Turnip curly top virus isolate', '<name type="scientific">Turnip curly top virus isolate</name>', 416861, 416862);

