package org.uniprot.store.config;

public enum UniProtDataType {
    ARBA,
    CROSSREF,
    DISEASE,
    GENECENTRIC,
    HELP,
    KEYWORD,
    PIR_ID_MAPPING,
    LITERATURE,
    PRECOMPUTED_ANNOTATION,
    PROTEOME,
    PUBLICATION,
    SUBCELLLOCATION,
    SUGGEST,
    TAXONOMY,
    UNIPARC,
    UNIPROTKB,
    UNIREF,
    UNIRULE,
    UNIPARC_CROSSREF,
    MAPTO_ID
}
